on:
  push:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Configure ownership settings to pi user
        run: sudo chown -R $(id -u):$(id -g) ~/Desktop/actions-runner/_work/flight-hunter/flight-hunter
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Copy environment to directory
        run: cp ~/Desktop/flight-hunter-env/.env .env
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
