on:
  push:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Copy env to directory
        run: cp ~/Desktop/flight-hunter-env/.env .env
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
