on:
  push:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Run the scripts
        run: ls -la
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
